version: '3'
services:
  # client
  tuic-client:
    image: kotahv/tuic-client:latest
    container_name: tuic-client
    restart: always
    network_mode: "host"
    volumes:
      - /path/to/config.json:/etc/tuic-client/config.json
  # server
  tuic-server:
    image: kotahv/tuic-server:latest
    container_name: tuic-server
    restart: always
    network_mode: "host"
    volumes:
      - /path/to/config.json:/etc/tuic-server/config.json
      - /path/to/ssl:/path/to/ssl